---
title: "201A Analysis Project"
output: github_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library (patchwork)
library(readr)
library(broom)
library(dbplyr)
library(viridis)
library(corrplot)
library(knitr)
library(janitor)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

### 201A Analysis Project 

### Julián Ponce


``` {r importing data}
senic_data =
  read_csv (file = "./data/SENIC.csv")%>%
janitor::clean_names()

senic_data =
  senic_data %>%
  #c is to include only these while -c is remove these
  subset(select = c(id, length, age,risk, beds,region,census ))
#exclude data for culture, xrays, msch, nurses, and svcs 


```


```{r check variable type}
sapply(senic_data, class)
```

Create a new chunk comman +opton+i 
Change region from numeric to factor 
```{r change variable type}
senic_data = senic_data%>%
  mutate(region = as.factor(region), 
        id = as.factor(id),
        age = as.numeric(age),
        length=as.numeric(length))%>%
  mutate(risk=(risk*.100))
  
senic_data1 =
  senic_data %>%
  #c is to include only these while -c is remove these
  subset(select = c(length, age,risk, beds,census   ))
#exclude data for culture, xrays, msch, nurses, and svcs 
skimr::skim(senic_data1) 
```

#Library Janitor needed for tabyl
```{r summary stats}

senic_data %>%
tabyl(region)%>%
knitr::kable(digits=3)
```

#1_Univariate
Histograms in case needed but i think SKIMR IS okay
```{r histograms 1}

histogram_age =
ggplot(senic_data, aes(x = age)) + 
  geom_histogram(bins =11, color="darkblue", fill="lightblue") + labs (title = "Figure 1.Age Distribution", x="Age", y ="Count") 

histogram_length=
ggplot(senic_data, aes(x = length)) + 
   geom_histogram(bins =11, color="darkblue", fill="lightblue") + labs (title = "Figure 2.Length of Stay Distribution", x="Length of Stay(Days)", y ="Count") 

histogram_risk =
ggplot(senic_data, aes(x = risk)) + 
   geom_histogram(bins =11, color="darkblue", fill="lightblue") + labs (title = "Figure 3.Infection Distribution", x="Infection Risk(Years)", y ="Count") 

histogram_beds =
ggplot(senic_data, aes(x = beds)) + 
   geom_histogram(bins =11, color="darkblue", fill="lightblue") + labs (title = "Figure 4. Bed Distribution", x="Number of Beds", y ="Count") 

histogram_census =
ggplot(senic_data, aes(x = census)) + 
     geom_histogram(bins =11, color="darkblue", fill="lightblue") + labs (title = "Figure 5.Census Distribution", x="Average Number of Hospital Patients Per Day", y ="Count") 

histogram_age+histogram_length
histogram_risk+histogram_beds+histogram_census
```

#2_Correlations -https://statsandr.com/blog/correlation-coefficient-and-correlation-test-in-r/

```{r correlations}

cor.test(senic_data$age, senic_data$length, method="pearson")
cor.test(senic_data$age, senic_data$risk, method="pearson")
ggplot(senic_data) +
  aes(x = age, y = length) +
  geom_point(colour = "#0c4c8a") +
  theme_minimal()


#corr matrix, run corrplot lib 

corrplot(cor(senic_data1),
  method = "number",
  type = "upper" # show only upper side
)

```


```{r anova 3}

one.way <- aov(length ~ region, data = senic_data)

one.way %>%  
    broom::tidy()%>% 
knitr::kable(digits=3)
```

## Regression #3
# Using gml or lm? 
```{r linear model}

linearmod = lm(length ~ age , data=senic_data)  # build linear regression model on full data
linearmod1 = lm(length ~ beds, data=senic_data)
linearmod2 = lm(length ~ census, data=senic_data) 
linearmod3 = lm(length ~risk , data=senic_data) 

linearmod %>%  
    broom::tidy()%>% 
knitr::kable(digits=3)

linearmod1 %>%  
    broom::tidy()%>% 
knitr::kable(digits=3)

linearmod2 %>%  
    broom::tidy()%>% 
knitr::kable(digits=3)

linearmod3 %>%  
    broom::tidy()%>% 
knitr::kable(digits=3)
```

```{r regression stratefied}
 senic_region1 =
senic_data %>% 
  filter(region == "1")

linearmod = lm(length ~ risk , data=senic_region1)  # build linear regression model on full data

linearmod %>%  
    broom::tidy()%>% 
knitr::kable(digits=3)


 senic_region2 =
senic_data %>% 
  filter(region == "2")

linearmod = lm(length ~  risk , data=senic_region2)  # build linear regression model on full data

linearmod %>%  
    broom::tidy()%>% 
knitr::kable(digits=3)

 senic_region3 =
senic_data %>% 
  filter(region == "3")

linearmod = lm(length ~  risk , data=senic_region3)  # build linear regression model on full data

linearmod %>%  
    broom::tidy()%>% 
knitr::kable(digits=3)


senic_region4 =
senic_data %>% 
  filter(region == "4")

linearmod = lm(length ~  risk , data=senic_region4)  # build linear regression model on full data

linearmod %>%  
    broom::tidy()%>% 
knitr::kable(digits=3)
```

